apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"fluent-bit-read"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"fluent-bit-read"},"subjects":[{"kind":"ServiceAccount","name":"fluent-bit","namespace":"kube-system"}]}
  creationTimestamp: "2026-02-21T00:21:13Z"
  name: fluent-bit-read
  resourceVersion: "937"
  uid: 04624e57-58de-4e4d-b2a7-ef8782ddc653
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: kube-system
